server:
  port: 8081
  max-http-request-header-size: 1024KB
  servlet:
    context-path: /dev
    session:
      timeout: 1800
  tomcat:
    relaxed-path-chars: <,>,[,\,],^,`,{,|,}
    relaxed-query-chars: <,>,[,\,],^,`,{,|,}

keycloak:
  base-url: ${KEYCLOAK_BASE_URL:http://localhost:8045/}
  realm: ${KEYCLOAK_REALM:campusio}
  realm-url: ${keycloak.base-url}/realms/${keycloak.realm}
  client:
    id: ${KEYCLOAK_CLIENT_ID:campusio-backend}
    secret: ${KEYCLOAK_CLIENT_SECRET:QoEgwydbkRN092L9FRgW3PkjHHnCjZTH}

develop-flag: true

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${keycloak.client.id}
            client-name: campusio-backend
            client-secret: ${keycloak.client.secret}
            provider: keycloak
            authorization-grant-type: authorization_code
            scope: openid, profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            authorization-uri: ${keycloak.realm-url}/protocol/openid-connect/auth
            jwk-set-uri: ${keycloak.realm-url}/protocol/openid-connect/certs
            token-uri: ${keycloak.realm-url}/protocol/openid-connect/token
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak.realm-url}/protocol/openid-connect/certs